-- Chapter 05. 01 도서 대여 시스템 테이블 생성
-- 시작 상태: public.members, public.books, public.loans가 존재하지 않음
-- 완료 상태: 세 테이블이 생성되고 데이터는 비어 있음
-- 주의: 이 파일은 기존 테이블을 자동으로 삭제하지 않습니다.
-- 세 테이블 생성은 하나의 트랜잭션으로 묶어 중간 실패 시 부분 생성 상태를 남기지 않습니다.

SELECT current_database();
SELECT current_user;
SELECT current_schema();
SHOW search_path;

BEGIN;

DO $$
BEGIN
    IF current_database() <> 'ai_database_book' THEN
        RAISE EXCEPTION
            '생성 중단: 현재 데이터베이스는 %입니다. ai_database_book에 연결하세요.',
            current_database();
    END IF;

    IF current_setting('transaction_read_only')::boolean THEN
        RAISE EXCEPTION
            '생성 중단: 현재 연결이 읽기 전용입니다.';
    END IF;

    IF to_regnamespace('public') IS NULL THEN
        RAISE EXCEPTION
            '생성 중단: public 스키마가 존재하지 않습니다.';
    END IF;

    IF NOT has_schema_privilege(current_user, 'public', 'USAGE') THEN
        RAISE EXCEPTION
            '생성 중단: 사용자 %에게 public 스키마 USAGE 권한이 없습니다.',
            current_user;
    END IF;

    IF NOT has_schema_privilege(current_user, 'public', 'CREATE') THEN
        RAISE EXCEPTION
            '생성 중단: 사용자 %에게 public 스키마 CREATE 권한이 없습니다.',
            current_user;
    END IF;

    IF to_regclass('public.members') IS NOT NULL
       OR to_regclass('public.books') IS NOT NULL
       OR to_regclass('public.loans') IS NOT NULL THEN
        RAISE EXCEPTION
            '생성 중단: Chapter 05 테이블 중 하나 이상이 이미 존재합니다. 기존 상태를 확인하거나 reset_library.sql을 검토하세요.';
    END IF;
END
$$;

-- 회원 한 행 = 회원 한 명
-- 이메일 고유성은 미확정이므로 UNIQUE를 적용하지 않습니다.
CREATE TABLE public.members (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    joined_at DATE NOT NULL
);

-- 도서 한 행 = 이 장에서 대여 대상으로 취급하는 간소화된 도서 항목 한 건
-- ISBN 존재 여부·고유성·복본 정책은 미확정이므로 NOT NULL·UNIQUE를 적용하지 않습니다.
CREATE TABLE public.books (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    author VARCHAR(100) NOT NULL,
    published_year INTEGER,
    isbn VARCHAR(20)
);

-- 대여 한 행 = 특정 회원이 특정 도서를 대여한 사건 한 건
-- returned_at은 미반납 상태를 표현하기 위해 NULL을 허용합니다.
-- 날짜 선후·동시 활성 대여 규칙은 Chapter 06에서 보완합니다.
CREATE TABLE public.loans (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id INTEGER NOT NULL REFERENCES public.members(id),
    book_id INTEGER NOT NULL REFERENCES public.books(id),
    borrowed_at DATE NOT NULL,
    due_at DATE NOT NULL,
    returned_at DATE
);

DO $$
DECLARE
    v_member_count bigint;
    v_book_count bigint;
    v_loan_count bigint;
BEGIN
    IF to_regclass('public.members') IS NULL
       OR to_regclass('public.books') IS NULL
       OR to_regclass('public.loans') IS NULL THEN
        RAISE EXCEPTION '생성 검증 실패: 세 테이블이 모두 생성되지 않았습니다.';
    END IF;

    SELECT COUNT(*) INTO v_member_count FROM public.members;
    SELECT COUNT(*) INTO v_book_count FROM public.books;
    SELECT COUNT(*) INTO v_loan_count FROM public.loans;

    IF v_member_count <> 0 OR v_book_count <> 0 OR v_loan_count <> 0 THEN
        RAISE EXCEPTION
            '생성 검증 실패: 새 테이블이 비어 있지 않습니다. members=%, books=%, loans=%',
            v_member_count, v_book_count, v_loan_count;
    END IF;
END
$$;

COMMIT;

SELECT
    to_regclass('public.members') AS members_table,
    to_regclass('public.books') AS books_table,
    to_regclass('public.loans') AS loans_table;

SELECT table_schema, table_name
FROM information_schema.tables
WHERE table_schema = 'public'
ORDER BY table_name;
